{% set name = "csv_trimming" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/csv_trimming-{{ version }}.tar.gz
  sha256: 17fa6a276a6a0e9c0eadd328ecf1947e638f580515870f351d32a225026b7ab3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - scipy
    - numpy
    - ugly_csv_generator >=1.1.4

test:
  imports:
    - csv_trimming
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LucaCappelletti94/csv_trimming
  summary: Package python to remove common ugliness from a csv-like file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
